{{- if (include "postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.chart.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secretAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ include "postgresql.passwordKey" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" (include "postgresql.secretName" .) "key" (include "postgresql.passwordKey" .) "providedValues" (list "global.postgresql.auth.password" "auth.password") "honorProvidedValues" true "context" $) }}
{{- end }}
