{{- if and .Values.agent.enabled (not .Values.agent.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "komari.agent.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  auto-discovery-key: {{ .Values.agent.auth.autoDiscoveryKey | quote }}
{{- end }}
