annotations:
  images: |
    - name: cloudflared
      image: docker.io/cloudflare/cloudflared:2026.7.2
  licenses: Apache-2.0
apiVersion: v2
appVersion: "2026.7.2"
dependencies:
  - name: common
    repository: file://../common
    version: 0.2.2
description: A remotely managed Cloudflare Tunnel connector.
home: https://github.com/community-helm-charts/helm-charts
keywords:
  - cloudflare
  - cloudflared
  - tunnel
maintainers:
  - name: community-helm-charts
    url: https://github.com/community-helm-charts/helm-charts
name: cloudflared
sources:
  - https://github.com/community-helm-charts/helm-charts/tree/main/charts/cloudflared
  - https://github.com/cloudflare/cloudflared
type: application
version: 1.1.1
