{{- if (include "mysql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secretAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ include "mysql.rootPasswordKey" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" (include "mysql.secretName" .) "key" (include "mysql.rootPasswordKey" .) "providedValues" (list "auth.rootPassword") "honorProvidedValues" true "context" $) }}
  {{- if (include "mysql.username" .) }}
  {{ include "mysql.passwordKey" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" (include "mysql.secretName" .) "key" (include "mysql.passwordKey" .) "providedValues" (list "auth.password") "honorProvidedValues" true "context" $) }}
  {{- end }}
{{- end }}
