{{- if and .Values.mysql.enabled .Values.activitypub.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost.mysql.initdbConfigMapName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: mysql
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  01-activitypub-database.sql: |
    CREATE DATABASE IF NOT EXISTS `{{ .Values.activitypub.database }}`;
    GRANT ALL ON `{{ .Values.activitypub.database }}`.* TO '{{ include "ghost.databaseUser" . }}'@'%';
{{- end }}
