{{- if (include "ghost.analytics.useTraefikIngress" .) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "ghost.analyticsStripPrefixMiddlewareName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  stripPrefix:
    prefixes:
      - /.ghost/analytics
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ghost.analyticsIngress.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "ghost.analyticsStripPrefixMiddlewareRef" . | quote }}
    {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.ingress.annotations .Values.commonAnnotations) "context" .) }}
    {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /.ghost/analytics
            pathType: Prefix
            backend:
              service:
                name: {{ include "ghost.analytics.fullname" . }}
                port:
                  name: http
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname | trunc 63 | trimSuffix "-" }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
