{{- if and .Values.ghost.enabled .Values.ghost.service.enabled .Values.ingress.enabled .Values.activitypub.enabled }}
apiVersion: {{ default (include "common.capabilities.ingress.apiVersion" .) .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ include "ghost.activitypubIngress.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.ingress.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    - host: {{ tpl .Values.ingress.hostname $ | quote }}
      http:
        paths:
          - path: /.ghost/activitypub
            pathType: Prefix
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "ghost.serviceName" .) "servicePort" "activitypub" "context" $) | nindent 14 }}
          - path: /.well-known/webfinger
            pathType: Exact
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "ghost.serviceName" .) "servicePort" "activitypub" "context" $) | nindent 14 }}
          - path: /.well-known/nodeinfo
            pathType: Exact
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "ghost.serviceName" .) "servicePort" "activitypub" "context" $) | nindent 14 }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ tpl .Values.ingress.hostname $ | quote }}
      secretName: {{ printf "%s-tls" ((tpl .Values.ingress.hostname $) | replace "*." "") | trunc 63 | trimSuffix "-" }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
