{{- if and .Values.ghost.persistence.enabled (not .Values.ghost.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost.contentPvcName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.ghost.persistence.labels "context" $) | nindent 4 }}
  {{- if or .Values.ghost.persistence.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.ghost.persistence.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.ghost.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.ghost.persistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.ghost.persistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ghost.persistence.size | quote }}
  {{- if .Values.ghost.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.ghost.persistence.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.ghost.persistence "global" .Values.global) | nindent 2 }}
{{- end }}
