{{- if (include "ghost.createDatabaseSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.databaseSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secretAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.mysql.enabled }}
  {{ include "ghost.databaseRootPasswordKey" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" (include "ghost.databaseSecretName" .) "key" (include "ghost.databaseRootPasswordKey" .) "providedValues" (list "mysql.auth.rootPassword") "honorProvidedValues" true "context" $) }}
  {{ include "ghost.databasePasswordKey" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" (include "ghost.databaseSecretName" .) "key" (include "ghost.databasePasswordKey" .) "providedValues" (list "mysql.auth.password") "honorProvidedValues" true "context" $) }}
  {{- else }}
  {{ include "ghost.databasePasswordKey" . }}: {{ required "externalDatabase.password is required when mysql.enabled=false and externalDatabase.existingSecret is empty" .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if (include "ghost.analytics.createSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.analytics.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secretAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ include "ghost.analytics.trackerTokenKey" . }}: {{ .Values.analytics.tinybird.trackerToken | b64enc | quote }}
  {{ include "ghost.analytics.adminTokenKey" . }}: {{ .Values.analytics.tinybird.adminToken | b64enc | quote }}
  {{ include "ghost.analytics.workspaceIdKey" . }}: {{ .Values.analytics.tinybird.workspaceId | b64enc | quote }}
{{- end }}
{{- if (include "ghost.smtp.createSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.smtp.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secretAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ include "ghost.smtp.passwordKey" . }}: {{ .Values.smtp.password | b64enc | quote }}
{{- end }}
