{{- if and .Values.ghost.enabled .Values.ghost.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.serviceName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.ghost.service.labels .Values.commonLabels) "context" .) }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
    app.kubernetes.io/component: ghost
  {{- if or .Values.ghost.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.ghost.service.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ghost.service.type }}
  {{- if and .Values.ghost.service.clusterIP (eq .Values.ghost.service.type "ClusterIP") }}
  clusterIP: {{ .Values.ghost.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.ghost.service.type "LoadBalancer") (eq .Values.ghost.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.ghost.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.ghost.service.type "LoadBalancer") .Values.ghost.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.ghost.service.loadBalancerClass }}
  {{- end }}
  {{- if and (eq .Values.ghost.service.type "LoadBalancer") .Values.ghost.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ghost.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.ghost.service.type "LoadBalancer") .Values.ghost.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.ghost.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.ghost.service.sessionAffinity }}
  sessionAffinity: {{ .Values.ghost.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.ghost.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.ghost.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.ghost.service.ports.http }}
      targetPort: http
      {{- if and (or (eq .Values.ghost.service.type "NodePort") (eq .Values.ghost.service.type "LoadBalancer")) .Values.ghost.service.nodePorts.http }}
      nodePort: {{ .Values.ghost.service.nodePorts.http }}
      {{- end }}
    {{- if .Values.activitypub.enabled }}
    - name: activitypub
      port: {{ .Values.activitypub.service.ports.http }}
      targetPort: activitypub
    {{- end }}
    {{- if .Values.ghost.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ghost.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.ghost.podLabels .Values.commonLabels) "context" .) }}
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: ghost
{{- end }}
