{{- if (include "ghost.trafficAnalytics.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.trafficAnalytics.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secretAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ include "ghost.trafficAnalytics.trackerTokenKey" . }}: {{ .Values.trafficAnalytics.tinybird.trackerToken | b64enc | quote }}
  {{ include "ghost.trafficAnalytics.adminTokenKey" . }}: {{ .Values.trafficAnalytics.tinybird.adminToken | b64enc | quote }}
  {{ include "ghost.trafficAnalytics.workspaceIdKey" . }}: {{ .Values.trafficAnalytics.tinybird.workspaceId | b64enc | quote }}
{{- end }}
