apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: connector
type: Opaque
stringData:
  token: {{ .Values.auth.tunnelToken | quote }}
